DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE PRODUTO (
IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , VALOR_EURO  NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

DELIMITER $$


CREATE TRIGGER TR_PRODUTO_B_I BEFORE INSERT ON PRODUTO FOR EACH ROW
BEGIN

	IF NEW.VALOR_REAL IS NULL AND NEW.VALOR_DOLAR IS NULL AND NEW.VALOR_EURO IS NULL THEN
	SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'INFORME UM VALOR';
    
    ELSEIF NEW.VALOR_REAL IS NOT NULL THEN
    SET NEW.VALOR_DOLAR = NEW.VALOR_REAL / 4.22;
    SET NEW.VALOR_EURO = NEW.VALOR_REAL / 4.67;
    
    ELSEIF NEW.VALOR_DOLAR IS NOT NULL THEN
    SET NEW.VALOR_REAL = NEW.VALOR_DOLAR * 4.22;
    SET NEW.VALOR_EURO = NEW.VALOR_DOLAR / 4.67;
    
    ELSE
    SET NEW.VALOR_REAL = NEW.VALOR_EURO * 4.67;
    SET NEW.VALOR_DOLAR = NEW.VALOR_EURO / 4.67;
    
	IF(NEW.VALOR_REAL / 4.22 <> NEW.VALOR_DOLAR OR NEW.VALOR_REAL / 4.67 <> NEW.VALOR_EURO) THEN
	SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HÁ UM ERRO NOS VALORES INSERIDOS';
    
    END IF;
    
    END IF;
	
END $$

CREATE TRIGGER TR_PRODUTO_B_U BEFORE UPDATE ON PRODUTO FOR EACH ROW
BEGIN

	IF NEW.VALOR_REAL IS NULL AND NEW.VALOR_DOLAR IS NULL AND NEW.VALOR_EURO IS NULL THEN
	SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'INFORME UM VALOR';
    
    ELSEIF NEW.VALOR_REAL IS NOT NULL THEN
    SET NEW.VALOR_DOLAR = NEW.VALOR_REAL / 4.22;
    SET NEW.VALOR_EURO = NEW.VALOR_REAL / 4.67;
    
    ELSEIF NEW.VALOR_DOLAR IS NOT NULL THEN
    SET NEW.VALOR_REAL = NEW.VALOR_DOLAR * 4.22;
    SET NEW.VALOR_EURO = NEW.VALOR_DOLAR / 4.67;
    
    ELSEIF NEW.VALOR_EURO IS NOT NULL THEN
    SET NEW.VALOR_REAL = NEW.VALOR_EURO * 4.67;
    SET NEW.VALOR_DOLAR = NEW.VALOR_EURO / 4.67;
    
	IF(NEW.VALOR_REAL / 4.22 <> NEW.VALOR_DOLAR OR NEW.VALOR_REAL / 4.67 <> NEW.VALOR_EURO) THEN
	SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HÁ UM ERRO NOS VALORES INSERIDOS';
    
    END IF;
    
    END IF;
	
END $$

DELIMITER ;

-- ANTES DE INSERIR OS VALORES
SELECT * FROM PRODUTO;

INSERT INTO PRODUTO (NOME, VALOR_REAL)VALUES('CELULAR', 200);
INSERT INTO PRODUTO (NOME, VALOR_REAL)VALUES('TABLET', 350);
INSERT INTO PRODUTO (NOME, VALOR_REAL, VALOR_DOLAR)VALUES('AGUA', 10, 30);
INSERT INTO PRODUTO (NOME, VALOR_DOLAR)VALUES('PEDRA', 20);
-- mensaem para realizar o teste de erro INSERT INTO PRODUTO (NOME, VALOR_EURO)VALUES('GELO', 10);
INSERT INTO PRODUTO (NOME, VALOR_DOLAR)VALUES('MAÇA', 30);
-- mensagem para realizar o teste de erro INSERT INTO PRODUTO (NOME) VALUES('MAÇA');

-- APÓS INSERIR OS VALORES
SELECT * FROM PRODUTO;	

UPDATE PRODUTO SET VALOR_REAL = 250 WHERE IDPRODUTO = 1;
UPDATE PRODUTO SET VALOR_REAL = 30 WHERE IDPRODUTO = 2;
UPDATE PRODUTO SET VALOR_EURO = 250 WHERE IDPRODUTO = 3;
UPDATE PRODUTO SET VALOR_DOLAR = 1 WHERE IDPRODUTO = 4;
UPDATE PRODUTO SET VALOR_REAL = 5 WHERE IDPRODUTO = 5;

-- APÓS UPDATE DOS VALORES
SELECT * FROM PRODUTO;	


/*
QUESTÃO:
1. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR E EURO DEVE SER CALCULADO

Valor para conversão 1 Real = 3,9005 Dólar
Valor para conversão 1 Real = 4,3684 Euro
*/